server:
  port: 11001
  context-path: /
spring:
  datasource:
    username: root
    password: root
    url:  jdbc:mysql://localhost:3306/zhangmutong
    driver-class-name: com.mysql.jdbc.Driver
#设置mvc页面跳转
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yy.pojo
#日志相关配置
logging:
  level: INFO
  path: D:/log/logs